#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

REMOTE="${HASS_REMOTE:-root@hass.homelab.lan}"
REMOTE_PATH="/homeassistant/custom_components/room_climate_controller"

echo "Deploying to ${REMOTE}:${REMOTE_PATH} ..."

rsync -av --delete \
    --exclude '__pycache__' \
    --exclude '*.pyc' \
    --exclude 'node_modules' \
    --exclude 'tests' \
    custom_components/room_climate_controller/ \
    "${REMOTE}:${REMOTE_PATH}/"

echo "Done. Restart Home Assistant to apply changes."
